#!/bin/sh

case "$1" in
  start)
    printf "Starting autorestart... "
    dbus-send --system --type=method_call --dest=com.overkiz.Application.Internal \
                 /com/overkiz/Application/Internal/Modules \
                 com.overkiz.Application.Internal.Modules.setRestart \
                 boolean:"true"
    echo "done."
  ;;
  stop)
    printf "Stopping autorestart... "
    dbus-send --system --type=method_call --dest=com.overkiz.Application.Internal \
                 /com/overkiz/Application/Internal/Modules \
                 com.overkiz.Application.Internal.Modules.setRestart \
                 boolean:"false"
    echo "done."
  ;;
  *)
    echo "Action '$1' is not supported."
    echo "Abort."
  ;;
esac

