local var_0_0 = require("Overkiz.HomeAutomation.Shared.IoHomecontrolOvp.Node.nodeModel")
local var_0_1 = require("Overkiz.HomeAutomation.Shared.IoHomecontrolOvp.Parameter.Public.FunctionalParameter12")
local var_0_2 = require("Overkiz.HomeAutomation.Shared.IoHomecontrolOvp.Parameter.Public.FunctionalParameter13")
local var_0_3 = require("Overkiz.HomeAutomation.Shared.IoHomecontrolOvp.Parameter.Object.CoexistenceIdentifierObject")
local var_0_4 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.ModePiece")
local var_0_5 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.FonctionDetectionOccupation")
local var_0_6 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.DetectionOccupation")
local var_0_7 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TemperatureMaxReglable")
local var_0_8 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TemperatureDeConsigneConfort")
local var_0_9 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TemperatureAbaissementModeProg")
local var_0_10 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TemperatureAbaissementModeAuto")
local var_0_11 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.DetectionFenetreOuverte")
local var_0_12 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.LangueIhm")
local var_0_13 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TypeProgrammation")
local var_0_14 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.DetectionOuvertureFenetre")
local var_0_15 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.DateHeure")
local var_0_16 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TemperatureAnticipationLocale")
local var_0_17 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TemperatureAmbianteLocale")
local var_0_18 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.IndexConso")
local var_0_19 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.EtatRegulateur")
local var_0_20 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.IdentiteMarque")
local var_0_21 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.IdentiteModele")
local var_0_22 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.IdentitePuissance")
local var_0_23 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.ValeurConsigneDerogee")
local var_0_24 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.ProgrammationHoraire")
local var_0_25 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.NiveauFonctionnelNatif")
local var_0_26 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.OffsetEtalonnageTemperature")
local var_0_27 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.AnnulationEffacement")
local var_0_28 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TauxDeMarche")
local var_0_29 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.CumulAbaissementSemaine")
local var_0_30 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.SeuilEffacementPiece")
local var_0_31 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.TemperatureDeConsigneEffective")
local var_0_32 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.DonneAdresseControleur")
local var_0_33 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.LumiereConsigne")
local var_0_34 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.LumiereEtat")
local var_0_35 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.LumiereEtatAutoLocal")
local var_0_36 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.LumiereTempo")
local var_0_37 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.LumiereTempoMemo")
local var_0_38 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.ECL.LumiereEtatDetectionPresence")
local var_0_39 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.ModeSsvPiece")
local var_0_40 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.TemperatureConsigneEffectiveSsv")
local var_0_41 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.TemperatureConsigneConfortSsv")
local var_0_42 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.ProgrammationHoraireSsv")
local var_0_43 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.TempoBoostSsv")
local var_0_44 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.ParametragesBoostSsv")
local var_0_45 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.TempoSechageSsv")
local var_0_46 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.ParametragesSechageSsv")
local var_0_47 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.EtatTemporaireSsv")
local var_0_48 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.EtatOccupationPieceSsv")
local var_0_49 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.EtatCapteurEnvironnementauxSsv")
local var_0_50 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.SSV.EtatErreur6Ssv")
local var_0_51 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Object.Atlantic.ApprentissageAutoprogram")
local var_0_52 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Object.Atlantic.ApprentissageAutoprogramSsv")
local var_0_53 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.factory")
local var_0_54 = {}

var_0_54.name = "ElectricalHeaterSubProfile"
var_0_54.SSV = "210002"
var_0_54.IC3 = "260000"
var_0_54.BD3_3 = "240002"

local function var_0_55(arg_1_0)
	return (string.format("%.2X%.2X%.2X", arg_1_0.generalinfo[2][8], arg_1_0.generalinfo[2][9], arg_1_0.generalinfo[2][10]))
end

function var_0_54.create(arg_2_0)
	var_0_53:create(var_0_1, arg_2_0)
	var_0_53:create(var_0_2, arg_2_0)

	if arg_2_0.manufacturer == var_0_0.manufacturers.Atlantic then
		var_0_53:create(var_0_32, arg_2_0)
		var_0_53:create(var_0_3, arg_2_0)
		var_0_53:create(var_0_20, arg_2_0)
		var_0_53:create(var_0_21, arg_2_0)
		var_0_53:create(var_0_25, arg_2_0)
		var_0_53:create(var_0_9, arg_2_0)
		var_0_53:create(var_0_18, arg_2_0)
		var_0_53:create(var_0_23, arg_2_0)
		var_0_53:create(var_0_29, arg_2_0)
		var_0_53:create(var_0_15, arg_2_0)

		if var_0_55(arg_2_0) == var_0_54.SSV or var_0_55(arg_2_0) == var_0_54.IC3 then
			var_0_53:create(var_0_39, arg_2_0)
			var_0_53:create(var_0_41, arg_2_0)
			var_0_53:create(var_0_42, arg_2_0)
			var_0_53:create(var_0_43, arg_2_0)
			var_0_53:create(var_0_44, arg_2_0)
			var_0_53:create(var_0_45, arg_2_0)
			var_0_53:create(var_0_46, arg_2_0)
			var_0_53:create(var_0_47, arg_2_0)
			var_0_53:create(var_0_40, arg_2_0)
			var_0_53:create(var_0_48, arg_2_0)
			var_0_53:create(var_0_49, arg_2_0)
			var_0_53:create(var_0_50, arg_2_0)
			var_0_53:create(var_0_52, arg_2_0)
		else
			var_0_53:create(var_0_4, arg_2_0)
			var_0_53:create(var_0_8, arg_2_0)
			var_0_53:create(var_0_11, arg_2_0)
			var_0_53:create(var_0_13, arg_2_0)
			var_0_53:create(var_0_24, arg_2_0)
			var_0_53:create(var_0_51, arg_2_0)

			if var_0_55(arg_2_0) == var_0_54.BD3_3 then
				var_0_53:create(var_0_33, arg_2_0)
				var_0_53:create(var_0_34, arg_2_0)
				var_0_53:create(var_0_35, arg_2_0)
				var_0_53:create(var_0_36, arg_2_0)
				var_0_53:create(var_0_37, arg_2_0)
				var_0_53:create(var_0_38, arg_2_0)
			end

			var_0_53:create(var_0_7, arg_2_0)
			var_0_53:create(var_0_10, arg_2_0)
			var_0_53:create(var_0_12, arg_2_0)
			var_0_53:create(var_0_5, arg_2_0)
			var_0_53:create(var_0_27, arg_2_0)
			var_0_53:create(var_0_30, arg_2_0)
			var_0_53:create(var_0_31, arg_2_0)
		end

		var_0_53:create(var_0_19, arg_2_0)
		var_0_53:create(var_0_14, arg_2_0)
		var_0_53:create(var_0_6, arg_2_0)
		var_0_53:create(var_0_16, arg_2_0)
		var_0_53:create(var_0_17, arg_2_0)
		var_0_53:create(var_0_22, arg_2_0)
		var_0_53:create(var_0_26, arg_2_0)
		var_0_53:create(var_0_28, arg_2_0)
	end
end

return var_0_54
