local var_0_0 = {}

var_0_0.name = "ZoneControlGenerator"

function var_0_0.create(arg_1_0, arg_1_1)
	local var_1_0 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_1_ProductModelName")
	local var_1_1 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_2_SerialNumber")
	local var_1_2 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_6_ProductType")
	local var_1_3 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_7_ZonesNumber")
	local var_1_4 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_8_ZonesMainCapabilities")
	local var_1_5 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_29_PuissanceThermiqueNominaleChauf")
	local var_1_6 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_31_PuissanceThermiqueNominaleECS")
	local var_1_7 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_32_EnergyConsumptionSensorCapability")
	local var_1_8 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_39_OperatingMode")
	local var_1_9 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_46_ZonesCurrentHeatingModes")
	local var_1_10 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_69_ZonesCurrentCoolingModes")
	local var_1_11 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_98_ZonesCurrentHeatingProfiles")
	local var_1_12 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_115_ZonesCurrentCoolingProfiles")
	local var_1_13 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_134_MinHeatingTargetTemperature")
	local var_1_14 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_135_MaxHeatingTargetTemperature")
	local var_1_15 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_136_ZonesComfortHeatingTargetTemperatures")
	local var_1_16 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_153_ZonesEcoHeatingTargetTemperatures")
	local var_1_17 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_187_MinCoolingTargetTemperature")
	local var_1_18 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_188_MaxCoolingTargetTemperature")
	local var_1_19 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_189_ZonesComfortCoolingTargetTemperatures")
	local var_1_20 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_206_ZonesEcoCoolingTargetTemperatures")
	local var_1_21 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_240_ZonesTargetTemperatures")
	local var_1_22 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_260_DHWTargetTemperature")
	local var_1_23 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_264_HeatingDerogationAvailability")
	local var_1_24 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_318_ThermalComfortSchedulingCapability")
	local var_1_25 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_319_TimeProgram1")
	local var_1_26 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_320_TimeProgram2")
	local var_1_27 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_321_TimeProgram3")
	local var_1_28 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_322_TimeProgram4")
	local var_1_29 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_323_ZonesActiveHeatingTimePrograms")
	local var_1_30 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_340_ZonesActiveCoolingTimePrograms")
	local var_1_31 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_369_AbsenceSchedulingCapability")
	local var_1_32 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_370_AbsenceHeatingTargetTemperature")
	local var_1_33 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_371_AbsenceCoolingTargetTemperature")
	local var_1_34 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_373_AbsenceRemainingTime")
	local var_1_35 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_375_AbsenceEndDateTime")
	local var_1_36 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_376_ZonesTemperatureSensorsAvailability")
	local var_1_37 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_393_ZonesTemperatures")
	local var_1_38 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_422_ZonesNames")
	local var_1_39 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_443_ZonesHeatingOnOffStates")
	local var_1_40 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_460_ZonesCoolingOnOffStates")
	local var_1_41 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_479_HeatingCoolingAutoSwitch")
	local var_1_42 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_484_ZonesManualHeatingTargetTemperatures")
	local var_1_43 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_501_ZonesManualCoolingTargetTemperatures")
	local var_1_44 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_559_ManualHeatingMinTemperature_Zone1")
	local var_1_45 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_560_ManualHeatingMinTemperature_Zone2")
	local var_1_46 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_561_ManualHeatingMinTemperature_Zone3")
	local var_1_47 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_562_ManualHeatingMinTemperature_Zone4")
	local var_1_48 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_563_ManualHeatingMinTemperature_Zone5")
	local var_1_49 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_564_ManualHeatingMinTemperature_Zone6")
	local var_1_50 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_565_ManualHeatingMinTemperature_Zone7")
	local var_1_51 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_566_ManualHeatingMinTemperature_Zone8")
	local var_1_52 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_610_ManualCoolingMinTemperature_Zone1")
	local var_1_53 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_611_ManualCoolingMinTemperature_Zone2")
	local var_1_54 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_612_ManualCoolingMinTemperature_Zone3")
	local var_1_55 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_613_ManualCoolingMinTemperature_Zone4")
	local var_1_56 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_614_ManualCoolingMinTemperature_Zone5")
	local var_1_57 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_615_ManualCoolingMinTemperature_Zone6")
	local var_1_58 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_616_ManualCoolingMinTemperature_Zone7")
	local var_1_59 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_617_ManualCoolingMinTemperature_Zone8")
	local var_1_60 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_661_ManualHeatingMaxTemperature_Zone1")
	local var_1_61 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_662_ManualHeatingMaxTemperature_Zone2")
	local var_1_62 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_663_ManualHeatingMaxTemperature_Zone3")
	local var_1_63 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_664_ManualHeatingMaxTemperature_Zone4")
	local var_1_64 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_665_ManualHeatingMaxTemperature_Zone5")
	local var_1_65 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_666_ManualHeatingMaxTemperature_Zone6")
	local var_1_66 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_667_ManualHeatingMaxTemperature_Zone7")
	local var_1_67 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_668_ManualHeatingMaxTemperature_Zone8")
	local var_1_68 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_712_ManualCoolingMaxTemperature_Zone1")
	local var_1_69 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_713_ManualCoolingMaxTemperature_Zone2")
	local var_1_70 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_714_ManualCoolingMaxTemperature_Zone3")
	local var_1_71 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_715_ManualCoolingMaxTemperature_Zone4")
	local var_1_72 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_716_ManualCoolingMaxTemperature_Zone5")
	local var_1_73 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_717_ManualCoolingMaxTemperature_Zone6")
	local var_1_74 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_718_ManualCoolingMaxTemperature_Zone7")
	local var_1_75 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_719_ManualCoolingMaxTemperature_Zone8")
	local var_1_76 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_730_ErrorCode")
	local var_1_77 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_733_DerogationOnOffState")
	local var_1_78 = require("Overkiz.HomeAutomation.Shared.IoHomecontrolOvp.Node.nodeModel")
	local var_1_79 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.factory")

	if arg_1_0.manufacturer == var_1_78.manufacturers.Atlantic then
		var_1_79:create(var_1_3, arg_1_0)
		var_1_79:create(var_1_0, arg_1_0)
		var_1_79:create(var_1_4, arg_1_0)
		var_1_79:create(var_1_36, arg_1_0)
		var_1_79:create(var_1_2, arg_1_0)
		var_1_79:create(var_1_23, arg_1_0)
		var_1_79:create(var_1_7, arg_1_0)
		var_1_79:create(var_1_24, arg_1_0)
		var_1_79:create(var_1_31, arg_1_0)
		var_1_79:create(var_1_8, arg_1_0)
		var_1_79:create(var_1_1, arg_1_0)
		var_1_79:create(var_1_39, arg_1_0, var_1_39.eightZonesRefresh)
		var_1_79:create(var_1_40, arg_1_0, var_1_40.eightZonesRefresh)
		var_1_79:create(var_1_21, arg_1_0)
		var_1_79:create(var_1_77, arg_1_0)
		var_1_79:create(var_1_37, arg_1_0)
		var_1_79:create(var_1_9, arg_1_0, var_1_9.eightZonesRefresh)
		var_1_79:create(var_1_10, arg_1_0, var_1_10.eightZonesRefresh)
		var_1_79:create(var_1_11, arg_1_0)
		var_1_79:create(var_1_12, arg_1_0)
		var_1_79:create(var_1_38, arg_1_0, var_1_38.eightZonesRefresh)
		var_1_79:create(var_1_76, arg_1_0)
		var_1_79:create(var_1_35, arg_1_0)
		var_1_79:create(var_1_41, arg_1_0)
		var_1_79:create(var_1_29, arg_1_0, var_1_29.eightZonesRefresh)
		var_1_79:create(var_1_30, arg_1_0, var_1_30.eightZonesRefresh)
		var_1_79:create(var_1_25, arg_1_0)
		var_1_79:create(var_1_26, arg_1_0)
		var_1_79:create(var_1_27, arg_1_0)
		var_1_79:create(var_1_28, arg_1_0)
		var_1_79:create(var_1_15, arg_1_0, var_1_15.eightZonesRefresh)
		var_1_79:create(var_1_16, arg_1_0, var_1_16.eightZonesRefresh)
		var_1_79:create(var_1_19, arg_1_0, var_1_19.eightZonesRefresh)
		var_1_79:create(var_1_20, arg_1_0, var_1_20.eightZonesRefresh)
		var_1_79:create(var_1_42, arg_1_0)
		var_1_79:create(var_1_43, arg_1_0)
		var_1_79:create(var_1_13, arg_1_0)
		var_1_79:create(var_1_14, arg_1_0)
		var_1_79:create(var_1_17, arg_1_0)
		var_1_79:create(var_1_18, arg_1_0)
		var_1_79:create(var_1_44, arg_1_0)
		var_1_79:create(var_1_45, arg_1_0)
		var_1_79:create(var_1_46, arg_1_0)
		var_1_79:create(var_1_47, arg_1_0)
		var_1_79:create(var_1_48, arg_1_0)
		var_1_79:create(var_1_49, arg_1_0)
		var_1_79:create(var_1_50, arg_1_0)
		var_1_79:create(var_1_51, arg_1_0)
		var_1_79:create(var_1_60, arg_1_0)
		var_1_79:create(var_1_61, arg_1_0)
		var_1_79:create(var_1_62, arg_1_0)
		var_1_79:create(var_1_63, arg_1_0)
		var_1_79:create(var_1_64, arg_1_0)
		var_1_79:create(var_1_65, arg_1_0)
		var_1_79:create(var_1_66, arg_1_0)
		var_1_79:create(var_1_67, arg_1_0)
		var_1_79:create(var_1_52, arg_1_0)
		var_1_79:create(var_1_53, arg_1_0)
		var_1_79:create(var_1_54, arg_1_0)
		var_1_79:create(var_1_55, arg_1_0)
		var_1_79:create(var_1_56, arg_1_0)
		var_1_79:create(var_1_57, arg_1_0)
		var_1_79:create(var_1_58, arg_1_0)
		var_1_79:create(var_1_59, arg_1_0)
		var_1_79:create(var_1_68, arg_1_0)
		var_1_79:create(var_1_69, arg_1_0)
		var_1_79:create(var_1_70, arg_1_0)
		var_1_79:create(var_1_71, arg_1_0)
		var_1_79:create(var_1_72, arg_1_0)
		var_1_79:create(var_1_73, arg_1_0)
		var_1_79:create(var_1_74, arg_1_0)
		var_1_79:create(var_1_75, arg_1_0)
		var_1_79:create(var_1_5, arg_1_0)
		var_1_79:create(var_1_6, arg_1_0)
		var_1_79:create(var_1_32, arg_1_0)
		var_1_79:create(var_1_33, arg_1_0)
		var_1_79:create(var_1_22, arg_1_0)
		var_1_79:create(var_1_34, arg_1_0)
	end
end

return var_0_0
