local var_0_0 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_1_ProductModelName")
local var_0_1 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_2_SerialNumber")
local var_0_2 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_3_RegulationName")
local var_0_3 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_4_SoftwareVersion")
local var_0_4 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_6_ProductType")
local var_0_5 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_7_ZonesNumber")
local var_0_6 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_8_ZonesMainCapabilities")
local var_0_7 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_25_DHWConfiguration")
local var_0_8 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_29_PuissanceThermiqueNominaleChauf")
local var_0_9 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_31_PuissanceThermiqueNominaleECS")
local var_0_10 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_32_EnergyConsumptionSensorCapability")
local var_0_11 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_34_TotalFossilEnergyConsumption")
local var_0_12 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_36_HeatingRelatedFossilEnergyConsumption")
local var_0_13 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_38_DHWRelatedFossilEnergyConsumption")
local var_0_14 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_39_OperatingMode")
local var_0_15 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_40_ZonesComfortHeatingModeAvailability")
local var_0_16 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_46_ZonesCurrentHeatingModes")
local var_0_17 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_92_CurrentDHWMode")
local var_0_18 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_98_ZonesCurrentHeatingProfiles")
local var_0_19 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_132_DHWCurrentProfile")
local var_0_20 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_134_MinHeatingTargetTemperature")
local var_0_21 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_135_MaxHeatingTargetTemperature")
local var_0_22 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_136_ZonesComfortHeatingTargetTemperatures")
local var_0_23 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_153_ZonesEcoHeatingTargetTemperatures")
local var_0_24 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_240_ZonesTargetTemperatures")
local var_0_25 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_257_ComfortTargetDHWTemperature")
local var_0_26 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_258_EcoTargetDHWTemperature")
local var_0_27 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_260_DHWTargetTemperature")
local var_0_28 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_264_HeatingDerogationAvailability")
local var_0_29 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_299_ZonesDerogationRemainingTimes")
local var_0_30 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_316_DHWDerogationAvailability")
local var_0_31 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_317_DHWBoostOnOff")
local var_0_32 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_318_ThermalComfortSchedulingCapability")
local var_0_33 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_319_TimeProgram1")
local var_0_34 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_320_TimeProgram2")
local var_0_35 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_321_TimeProgram3")
local var_0_36 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_322_TimeProgram4")
local var_0_37 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_323_ZonesActiveHeatingTimePrograms")
local var_0_38 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_358_DHWProgramming")
local var_0_39 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_369_AbsenceSchedulingCapability")
local var_0_40 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_370_AbsenceHeatingTargetTemperature")
local var_0_41 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_373_AbsenceRemainingTime")
local var_0_42 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_375_AbsenceEndDateTime")
local var_0_43 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_376_ZonesTemperatureSensorsAvailability")
local var_0_44 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_393_ZonesTemperatures")
local var_0_45 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_410_OutsideTemperatureSensorAvailability")
local var_0_46 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_411_OutsideTemperature")
local var_0_47 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_422_ZonesNames")
local var_0_48 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_443_ZonesHeatingOnOffStates")
local var_0_49 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_477_DHWOnOffState")
local var_0_50 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_730_ErrorCode")
local var_0_51 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Serv_733_DerogationOnOffState")
local var_0_52 = require("Overkiz.HomeAutomation.Shared.IoHomecontrolOvp.Node.nodeModel")
local var_0_53 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.factory")
local var_0_54 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Factory.atlanticPassApcParametersFactory")
local var_0_55 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.Parameter.Private.Atlantic.PassAPC.Diagnostics.PassApcDiagnosticParameters")
local var_0_56 = require("Overkiz.HomeAutomation.Protocol.IoHomecontrol.log")
local var_0_57 = {}

var_0_57.name = "HeatingAndCoolingGeneratorBoiler"

function var_0_57.create(arg_1_0, arg_1_1)
	if arg_1_0.manufacturer == var_0_52.manufacturers.Atlantic then
		var_0_53:create(var_0_5, arg_1_0)
		var_0_53:create(var_0_0, arg_1_0)
		var_0_53:create(var_0_6, arg_1_0)
		var_0_53:create(var_0_43, arg_1_0)
		var_0_53:create(var_0_7, arg_1_0)
		var_0_53:create(var_0_45, arg_1_0)
		var_0_53:create(var_0_10, arg_1_0)
		var_0_53:create(var_0_4, arg_1_0)
		var_0_53:create(var_0_28, arg_1_0)
		var_0_53:create(var_0_30, arg_1_0)
		var_0_53:create(var_0_32, arg_1_0)
		var_0_53:create(var_0_39, arg_1_0)
		var_0_53:create(var_0_14, arg_1_0)
		var_0_53:create(var_0_1, arg_1_0)
		var_0_53:create(var_0_15, arg_1_0)
		var_0_53:create(var_0_49, arg_1_0)
		var_0_53:create(var_0_48, arg_1_0)
		var_0_53:create(var_0_24, arg_1_0)
		var_0_53:create(var_0_51, arg_1_0)
		var_0_53:create(var_0_44, arg_1_0)
		var_0_53:create(var_0_16, arg_1_0)
		var_0_53:create(var_0_31, arg_1_0)
		var_0_53:create(var_0_18, arg_1_0)
		var_0_53:create(var_0_29, arg_1_0)
		var_0_53:create(var_0_47, arg_1_0)
		var_0_53:create(var_0_50, arg_1_0)
		var_0_53:create(var_0_42, arg_1_0)
		var_0_53:create(var_0_37, arg_1_0)
		var_0_53:create(var_0_33, arg_1_0)
		var_0_53:create(var_0_34, arg_1_0)
		var_0_53:create(var_0_35, arg_1_0)
		var_0_53:create(var_0_36, arg_1_0)
		var_0_53:create(var_0_22, arg_1_0)
		var_0_53:create(var_0_23, arg_1_0)
		var_0_53:create(var_0_20, arg_1_0)
		var_0_53:create(var_0_21, arg_1_0)
		var_0_53:create(var_0_40, arg_1_0)
		var_0_53:create(var_0_11, arg_1_0)
		var_0_53:create(var_0_12, arg_1_0)
		var_0_53:create(var_0_13, arg_1_0)
		var_0_53:create(var_0_8, arg_1_0)
		var_0_53:create(var_0_9, arg_1_0)
		var_0_53:create(var_0_2, arg_1_0)
		var_0_53:create(var_0_3, arg_1_0)
		var_0_53:create(var_0_17, arg_1_0)
		var_0_53:create(var_0_19, arg_1_0)
		var_0_53:create(var_0_25, arg_1_0)
		var_0_53:create(var_0_26, arg_1_0)
		var_0_53:create(var_0_27, arg_1_0)
		var_0_53:create(var_0_46, arg_1_0)
		var_0_53:create(var_0_41, arg_1_0)
		var_0_53:create(var_0_38, arg_1_0)

		local var_1_0 = var_0_54:create(var_0_55.PassAPCBoiler)

		for iter_1_0, iter_1_1 in ipairs(var_1_0) do
			var_0_56:info("Factory : Create Parameter " .. iter_1_1.name .. " for node " .. arg_1_0.address)
			var_0_53:create(iter_1_1, arg_1_0)
		end
	end
end

return var_0_57
