#!/bin/sh

set -e

name="${2:-ubi}"
case $1 in
start)
	for sys in /sys/class/mtd/mtd[0-9]; do
		if [ "$(cat $sys/name)" = "$name" ]; then
			id=${sys#/sys/class/mtd/mtd}
			break;
		fi
	done 2>/dev/null
	num=$(ls -1 /dev/ubi[0-9] 2>/dev/null | wc -l)
	[ -n "$id" ] && ubiattach -m $id -d $num /dev/ubi_ctrl
	;;
stop)
	for sys in /sys/class/ubi/ubi[0-9]; do
		id=$(cat $sys/mtd_num)
		if [ "$(cat /sys/class/mtd/mtd$id/name)" = "$name" ]; then
			num=${sys#/sys/class/ubi/ubi}
			break;
		fi
	done 2>/dev/null
	[ -n "$num" ] && ubidetach -d $num /dev/ubi_ctrl
esac
