-- chunkname: @./gateway/io-somfy-table-values.module

local TableValues = {}

function TableValues.getString(title, index)
	local chosenTable = TableValues.getTable(title)
	local value = chosenTable[index]

	return value
end

function TableValues.getTable(title)
	local Last_Events_Type_Of_Last_Stop = {
		"RADIO_EVT_UNKNOWN",
		"RADIO_EVT_RTX_REACH_ANGULAR_POSITION",
		"RADIO_EVT_RTX_REACH_EXPLICIT_POSITION",
		"APPLI_EVT_STACK_OVERCROWDING",
		"APPLI_EVT_STACK_OVERFLOW",
		"APPLI_EVT_CONFIG_HAS_BEEN_MODIFIED",
		[36868] = "EVT_UNROLL,",
		[34062] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34073] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34093] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[36866] = "APPLI_STOP_DWP",
		[34060] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340141] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34091] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[36864] = "APPLI_STOP_IO",
		[34058] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340125] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34089] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340100] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34056] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340109] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34087] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340105] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34054] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340106] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34085] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340107] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34052] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340108] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34083] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340104] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34050] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340111] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34081] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[49160] = "APPLI_MVT_EVT_TYPE_SENSOR_ERROR",
		[34048] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340112] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[33792] = "RADIO_EVT_RTX_MOVE_TO_IP",
		[49158] = "APPLI_MVT_EVT_TYPE_RETURN_LONGFEEDBACK",
		[33536] = "RADIO_EVT_RTX_STOP",
		[340113] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[33280] = "RADIO_EVT_RTX_WINK",
		[49156] = "APPLI_MVT_EVT_TYPE_SHORTFEEDBACK",
		[33024] = "RADIO_EVT_RTX_UNROLL",
		[32768] = "RADIO_EVT_RTX_ROL / SET_LIGHT",
		[34075] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[49154] = "APPLI_STOP_EVT_TYPE_THERMAL",
		[340114] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340115] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[49408] = "EMS_STOP_BECAUSE_SINE_WAVE_IS_MISSING",
		[49152] = "APPLI_STOP_EVT_TYPE_TUBE",
		[340116] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340120] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34071] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340134] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340122] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340123] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34069] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340118] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340124] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34077] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34067] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340102] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34098] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340128] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34065] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340119] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34096] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[36869] = "EVT_STOP",
		[34063] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340103] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34094] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[36867] = "EVT_ROLL",
		[34061] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340129] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34092] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[36865] = "APPLI_STOP_WT",
		[34059] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34218] = "RADIO_EVT_RTX_MOVE_TO_SP (AA : target 0%-100%)",
		[34090] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340130] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34057] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340117] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34088] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340131] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34055] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340101] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34086] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340132] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34053] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340133] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34084] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340121] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34051] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340135] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34082] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[49161] = "APPLI_MVT_EVT_TYPE_OBSTACLE_CLEARANCE",
		[34049] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340136] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34080] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[49159] = "APPLI_MVT_EVT_TYPE_SLOWFEEDBACK",
		[340137] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340138] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34078] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[49157] = "APPLI_MVT_EVT_TYPE_LONGFEEDBACK",
		[340139] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340140] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34076] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[49155] = "APPLI_STOP_EVT_TYPE_REQUEST",
		[34079] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340143] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34074] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[49153] = "APPLI_STOP_EVT_TYPE_ELD",
		[340144] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340145] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34072] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340142] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340146] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340147] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34070] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340126] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340148] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34068] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340110] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34099] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34066] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[340127] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34097] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[34064] = "RADIO_EVT_RTX_MOVE_TO_SP",
		[16298] = "EMS frames (in binary, first 0 is D then frame in binary)",
		[34095] = "RADIO_EVT_RTX_MOVE_TO_SP"
	}

	if title == "Last_Events_Type_Of_Last_Stop" then
		return Last_Events_Type_Of_Last_Stop
	end

	local IP_infos = {
		[0] = "Automatic / NotSet / NotValidated / ProductUpperThanTheIP",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheIP",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheIP",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheIP",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheIP",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheIP",
		"Automatic / NotSet / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / ProductUpperThanTheIP",
		"Automatic / NotSet / Validated / ProductUpperThanTheIP",
		"Automatic / NotSet / Validated / ProductUpperThanTheIP",
		"Automatic / NotSet / Validated / ProductUpperThanTheIP",
		"Automatic / NotSet / Validated / ProductLowerThanTheIP",
		"Automatic / NotSet / Validated / ProductLowerThanTheIP",
		"Automatic / NotSet / Validated / ProductLowerThanTheIP",
		"Automatic / NotSet / Validated / ProductLowerThanTheIP",
		"Automatic / NotSet / Validated / ProductAtTheIP",
		"Automatic / NotSet / Validated / ProductAtTheIP",
		"Automatic / NotSet / Validated / ProductAtTheIP",
		"Automatic / NotSet / Validated / ProductAtTheIP",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductLowerThanTheIP",
		"Automatic / Set / NotValidated / ProductLowerThanTheIP",
		"Automatic / Set / NotValidated / ProductLowerThanTheIP",
		"Automatic / Set / NotValidated / ProductLowerThanTheIP",
		nil,
		"Automatic / Set / NotValidated / ProductAtTheIP",
		"Automatic / Set / NotValidated / ProductAtTheIP",
		"Automatic / Set / NotValidated / ProductAtTheIP",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / Validated / ProductUpperThanTheIP",
		"Automatic / Set / Validated / ProductUpperThanTheIP",
		"Automatic / Set / Validated / ProductUpperThanTheIP",
		"Automatic / Set / Validated / ProductUpperThanTheIP",
		"Automatic / Set / Validated / ProductLowerThanTheIP",
		"Automatic / Set / Validated / ProductLowerThanTheIP",
		"Automatic / Set / Validated / ProductLowerThanTheIP",
		"Automatic / Set / Validated / ProductLowerThanTheIP",
		"Automatic / Set / Validated / ProductAtTheIP",
		"Automatic / Set / Validated / ProductAtTheIP",
		"Automatic / Set / Validated / ProductAtTheIP",
		"Automatic / Set / Validated / ProductAtTheIP",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / ProductUpperThanTheIP",
		"Manual / NotSet / NotValidated / ProductUpperThanTheIP",
		"Manual / NotSet / NotValidated / ProductUpperThanTheIP",
		"Manual / NotSet / NotValidated / ProductUpperThanTheIP",
		"Manual / NotSet / NotValidated / ProductLowerThanTheIP",
		"Manual / NotSet / NotValidated / ProductLowerThanTheIP",
		"Manual / NotSet / NotValidated / ProductLowerThanTheIP",
		"Manual / NotSet / NotValidated / ProductLowerThanTheIP",
		"Manual / NotSet / NotValidated / ProductAtTheIP",
		"Manual / NotSet / NotValidated / ProductAtTheIP",
		"Manual / NotSet / NotValidated / ProductAtTheIP",
		"Manual / NotSet / NotValidated / ProductAtTheIP",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / Validated / ProductUpperThanTheIP",
		"Manual / NotSet / Validated / ProductUpperThanTheIP",
		"Manual / NotSet / Validated / ProductUpperThanTheIP",
		"Manual / NotSet / Validated / ProductUpperThanTheIP",
		"Manual / NotSet / Validated / ProductLowerThanTheIP",
		"Manual / NotSet / Validated / ProductLowerThanTheIP",
		"Manual / NotSet / Validated / ProductLowerThanTheIP",
		"Manual / NotSet / Validated / ProductLowerThanTheIP",
		"Manual / NotSet / Validated / ProductAtTheIP",
		"Manual / NotSet / Validated / ProductAtTheIP",
		"Manual / NotSet / Validated / ProductAtTheIP",
		"Manual / NotSet / Validated / ProductAtTheIP",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / Set / NotValidated / ProductUpperThanTheIP",
		"Manual / Set / NotValidated / ProductUpperThanTheIP",
		"Manual / Set / NotValidated / ProductUpperThanTheIP",
		"Manual / Set / NotValidated / ProductUpperThanTheIP",
		"Manual / Set / NotValidated / ProductLowerThanTheIP",
		"Manual / Set / NotValidated / ProductLowerThanTheIP",
		"Manual / Set / NotValidated / ProductLowerThanTheIP",
		"Manual / Set / NotValidated / ProductLowerThanTheIP",
		"Manual / Set / NotValidated / ProductAtTheIP",
		"Manual / Set / NotValidated / ProductAtTheIP",
		"Manual / Set / NotValidated / ProductAtTheIP",
		"Manual / Set / NotValidated / ProductAtTheIP",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / Validated / ProductUpperThanTheIP",
		"Manual / Set / Validated / ProductUpperThanTheIP",
		"Manual / Set / Validated / ProductUpperThanTheIP",
		"Manual / Set / Validated / ProductUpperThanTheIP",
		"Manual / Set / Validated / ProductLowerThanTheIP",
		"Manual / Set / Validated / ProductLowerThanTheIP",
		"Manual / Set / Validated / ProductLowerThanTheIP",
		"Manual / Set / Validated / ProductLowerThanTheIP",
		"Manual / Set / Validated / ProductAtTheIP",
		"Manual / Set / Validated / ProductAtTheIP",
		"Manual / Set / Validated / ProductAtTheIP",
		"Manual / Set / Validated / ProductAtTheIP",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheIP",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheIP",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheIP",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheIP",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheIP",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheIP",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheIP",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheIP",
		"Automatic / NotSet / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / ProductAtTheIP",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / ProductUpperThanTheIP",
		"Automatic / NotSet / Validated / ProductUpperThanTheIP",
		"Automatic / NotSet / Validated / ProductUpperThanTheIP",
		"Automatic / NotSet / Validated / ProductUpperThanTheIP",
		"Automatic / NotSet / Validated / ProductLowerThanTheIP",
		"Automatic / NotSet / Validated / ProductLowerThanTheIP",
		"Automatic / NotSet / Validated / ProductLowerThanTheIP",
		"Automatic / NotSet / Validated / ProductLowerThanTheIP",
		"Automatic / NotSet / Validated / ProductAtTheIP",
		"Automatic / NotSet / Validated / ProductAtTheIP",
		nil,
		"Automatic / NotSet / Validated / ProductAtTheIP",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductUpperThanTheIP",
		"Automatic / Set / NotValidated / ProductLowerThanTheIP",
		"Automatic / Set / NotValidated / ProductLowerThanTheIP",
		"Automatic / Set / NotValidated / ProductLowerThanTheIP",
		"Automatic / Set / NotValidated / ProductLowerThanTheIP",
		"Automatic / Set / NotValidated / ProductAtTheIP",
		"Automatic / Set / NotValidated / ProductAtTheIP",
		"Automatic / Set / NotValidated / ProductAtTheIP",
		"Automatic / Set / NotValidated / ProductAtTheIP",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / Validated / ProductUpperThanTheIP",
		"Automatic / Set / Validated / ProductUpperThanTheIP",
		"Automatic / Set / Validated / ProductUpperThanTheIP",
		"Automatic / Set / Validated / ProductUpperThanTheIP",
		"Automatic / Set / Validated / ProductLowerThanTheIP",
		"Automatic / Set / Validated / ProductLowerThanTheIP",
		"Automatic / Set / Validated / ProductLowerThanTheIP",
		"Automatic / Set / Validated / ProductLowerThanTheIP",
		"Automatic / Set / Validated / ProductAtTheIP",
		"Automatic / Set / Validated / ProductAtTheIP",
		"Automatic / Set / Validated / ProductAtTheIP",
		"Automatic / Set / Validated / ProductAtTheIP",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / ProductUpperThanTheIP",
		"Manual / NotSet / NotValidated / ProductUpperThanTheIP",
		"Manual / NotSet / NotValidated / ProductUpperThanTheIP",
		"Manual / NotSet / NotValidated / ProductUpperThanTheIP",
		"Manual / NotSet / NotValidated / ProductLowerThanTheIP",
		"Manual / NotSet / NotValidated / ProductLowerThanTheIP",
		"Manual / NotSet / NotValidated / ProductLowerThanTheIP",
		"Manual / NotSet / NotValidated / ProductLowerThanTheIP",
		"Manual / NotSet / NotValidated / ProductAtTheIP",
		"Manual / NotSet / NotValidated / ProductAtTheIP",
		"Manual / NotSet / NotValidated / ProductAtTheIP",
		"Manual / NotSet / NotValidated / ProductAtTheIP",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / Validated / ProductUpperThanTheIP",
		"Manual / NotSet / Validated / ProductUpperThanTheIP",
		"Manual / NotSet / Validated / ProductUpperThanTheIP",
		"Manual / NotSet / Validated / ProductUpperThanTheIP",
		"Manual / NotSet / Validated / ProductLowerThanTheIP",
		"Manual / NotSet / Validated / ProductLowerThanTheIP",
		"Manual / NotSet / Validated / ProductLowerThanTheIP",
		"Manual / NotSet / Validated / ProductLowerThanTheIP",
		"Manual / NotSet / Validated / ProductAtTheIP",
		"Manual / NotSet / Validated / ProductAtTheIP",
		"Manual / NotSet / Validated / ProductAtTheIP",
		"Manual / NotSet / Validated / ProductAtTheIP",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / Set / NotValidated / ProductUpperThanTheIP",
		"Manual / Set / NotValidated / ProductUpperThanTheIP",
		"Manual / Set / NotValidated / ProductUpperThanTheIP",
		"Manual / Set / NotValidated / ProductUpperThanTheIP",
		"Manual / Set / NotValidated / ProductLowerThanTheIP",
		"Manual / Set / NotValidated / ProductLowerThanTheIP",
		"Manual / Set / NotValidated / ProductLowerThanTheIP",
		"Manual / Set / NotValidated / ProductLowerThanTheIP",
		"Manual / Set / NotValidated / ProductAtTheIP",
		"Manual / Set / NotValidated / ProductAtTheIP",
		"Manual / Set / NotValidated / ProductAtTheIP",
		"Manual / Set / NotValidated / ProductAtTheIP",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / Validated / ProductUpperThanTheIP",
		"Manual / Set / Validated / ProductUpperThanTheIP",
		"Manual / Set / Validated / ProductUpperThanTheIP",
		"Manual / Set / Validated / ProductUpperThanTheIP",
		"Manual / Set / Validated / ProductLowerThanTheIP",
		"Manual / Set / Validated / ProductLowerThanTheIP",
		"Manual / Set / Validated / ProductLowerThanTheIP",
		"Manual / Set / Validated / ProductLowerThanTheIP",
		"Manual / Set / Validated / ProductAtTheIP",
		"Manual / Set / Validated / ProductAtTheIP",
		"Manual / Set / Validated / ProductAtTheIP",
		"Manual / Set / Validated / ProductAtTheIP",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation"
	}

	if title == "IP_infos" then
		return IP_infos
	end

	local Rotation_Direction = {
		[0] = "CCW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CCW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CCW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CCW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CCW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Automatic / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Manual / NeverFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Manual / NeverFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Manual / NeverFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Manual / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Manual / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Manual / NeverFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Manual / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Manual / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Manual / NeverFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Manual / AlreadyFound / SearchHasEnded / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Manual / AlreadyFound / SearchHasEnded / SetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Manual / AlreadyFound / SearchInProgress / NotSetByTheOEM / SetByTheInstallator / FoundByAlgo3",
		"CW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo1",
		"CW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo2",
		"CW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / NotSetByTheInstallator / FoundByAlgo3",
		"CW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / NeverFound OR ManuallySet",
		"CW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo1",
		"CW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo2",
		"CW / Manual / AlreadyFound / SearchInProgress / SetByTheOEM / SetByTheInstallator / FoundByAlgo3"
	}

	if title == "Rotation_Direction" then
		return Rotation_Direction
	end

	local Upper_End_Limit_Infos = {
		[0] = "Automatic / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductAtTheUpEndLimit",
		"Automatic / Set / Validated / ProductAtTheUpEndLimit",
		"Automatic / Set / Validated / ProductAtTheUpEndLimit",
		"Automatic / Set / Validated / ProductAtTheUpEndLimit",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductAtTheUpEndLimit",
		"Manual / NotSet / Validated / ProductAtTheUpEndLimit",
		"Manual / NotSet / Validated / ProductAtTheUpEndLimit",
		"Manual / NotSet / Validated / ProductAtTheUpEndLimit",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductAtTheUpEndLimit",
		"Manual / Set / NotValidated / ProductAtTheUpEndLimit",
		"Manual / Set / NotValidated / ProductAtTheUpEndLimit",
		"Manual / Set / NotValidated / ProductAtTheUpEndLimit",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / Validated / ProductAtTheUpEndLimit",
		"Manual / Set / Validated / ProductAtTheUpEndLimit",
		"Manual / Set / Validated / ProductAtTheUpEndLimit",
		"Manual / Set / Validated / ProductAtTheUpEndLimit",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheUpEndLimit",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheUpEndLimit",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Automatic / Set / Validated / ProductAtTheUpEndLimit",
		"Automatic / Set / Validated / ProductAtTheUpEndLimit",
		"Automatic / Set / Validated / ProductAtTheUpEndLimit",
		"Automatic / Set / Validated / ProductAtTheUpEndLimit",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheUpEndLimit",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / NotSet / Validated / ProductAtTheUpEndLimit",
		"Manual / NotSet / Validated / ProductAtTheUpEndLimit",
		"Manual / NotSet / Validated / ProductAtTheUpEndLimit",
		"Manual / NotSet / Validated / ProductAtTheUpEndLimit",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / NotValidated / ProductAtTheUpEndLimit",
		"Manual / Set / NotValidated / ProductAtTheUpEndLimit",
		"Manual / Set / NotValidated / ProductAtTheUpEndLimit",
		"Manual / Set / NotValidated / ProductAtTheUpEndLimit",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheUpEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheUpEndLimit",
		"Manual / Set / Validated / ProductAtTheUpEndLimit",
		"Manual / Set / Validated / ProductAtTheUpEndLimit",
		"Manual / Set / Validated / ProductAtTheUpEndLimit",
		"Manual / Set / Validated / ProductAtTheUpEndLimit",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation"
	}

	if title == "Upper_End_Limit_Infos" then
		return Upper_End_Limit_Infos
	end

	local Lower_End_Limit_Infos = {
		[0] = "Automatic / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductAtTheDownEndLimit",
		"Automatic / Set / Validated / ProductAtTheDownEndLimit",
		"Automatic / Set / Validated / ProductAtTheDownEndLimit",
		"Automatic / Set / Validated / ProductAtTheDownEndLimit",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductAtTheDownEndLimit",
		"Manual / NotSet / Validated / ProductAtTheDownEndLimit",
		"Manual / NotSet / Validated / ProductAtTheDownEndLimit",
		"Manual / NotSet / Validated / ProductAtTheDownEndLimit",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductAtTheDownEndLimit",
		"Manual / Set / NotValidated / ProductAtTheDownEndLimit",
		"Manual / Set / NotValidated / ProductAtTheDownEndLimit",
		"Manual / Set / NotValidated / ProductAtTheDownEndLimit",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / Validated / ProductAtTheDownEndLimit",
		"Manual / Set / Validated / ProductAtTheDownEndLimit",
		"Manual / Set / Validated / ProductAtTheDownEndLimit",
		"Manual / Set / Validated / ProductAtTheDownEndLimit",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / NotValidated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / Validated / ProductAtTheDownEndLimit",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / NotSet / Validated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / Set / NotValidated / ProductAtTheDownEndLimit",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / NotValidated / UndeterminatedSituation",
		"Automatic / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Automatic / Set / Validated / ProductAtTheDownEndLimit",
		"Automatic / Set / Validated / ProductAtTheDownEndLimit",
		"Automatic / Set / Validated / ProductAtTheDownEndLimit",
		"Automatic / Set / Validated / ProductAtTheDownEndLimit",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Automatic / Set / Validated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Manual / NotSet / NotValidated / ProductAtTheDownEndLimit",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / NotValidated / UndeterminatedSituation",
		"Manual / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / NotSet / Validated / ProductAtTheDownEndLimit",
		"Manual / NotSet / Validated / ProductAtTheDownEndLimit",
		"Manual / NotSet / Validated / ProductAtTheDownEndLimit",
		"Manual / NotSet / Validated / ProductAtTheDownEndLimit",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / NotSet / Validated / UndeterminatedSituation",
		"Manual / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / NotValidated / ProductAtTheDownEndLimit",
		"Manual / Set / NotValidated / ProductAtTheDownEndLimit",
		"Manual / Set / NotValidated / ProductAtTheDownEndLimit",
		"Manual / Set / NotValidated / ProductAtTheDownEndLimit",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / NotValidated / UndeterminatedSituation",
		"Manual / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / Validated / ProductUpperThanTheDownEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / Validated / ProductLowerThanTheDownEndLimit",
		"Manual / Set / Validated / ProductAtTheDownEndLimit",
		"Manual / Set / Validated / ProductAtTheDownEndLimit",
		"Manual / Set / Validated / ProductAtTheDownEndLimit",
		"Manual / Set / Validated / ProductAtTheDownEndLimit",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation",
		"Manual / Set / Validated / UndeterminatedSituation"
	}

	if title == "Lower_End_Limit_Infos" then
		return Lower_End_Limit_Infos
	end

	local Actuator_Status = {
		[0] = "Usage Not-Set Not-Paired",
		"Usage Set Not-Paired",
		"Usage Not-Set Paired",
		"Usage Set Paired",
		"Radio Setting Mode",
		"WT Ergo Setting Mode",
		"WT Shunt Setting Mode",
		"Config Mode Asked By Radio",
		"Config Mode Asked By WT Ergo",
		"Config Mode Asked By WT Shunt",
		"Double Power Cut Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"!!! Undefined Mode",
		"Thermal Protection Activated / Usage Not-Set Not-Paired",
		"Thermal Protection Activated / Usage Set Not-Paired",
		"Thermal Protection Activated / Usage Not-Set Paired",
		"Thermal Protection Activated / Usage Set Paired",
		"Thermal Protection Activated / Radio Setting Mode",
		"Thermal Protection Activated / WT Ergo Setting Mode",
		"Thermal Protection Activated / WT Shunt Setting Mode",
		"Thermal Protection Activated / Config Mode Asked By Radio",
		"Thermal Protection Activated / Config Mode Asked By WT Ergo",
		"Thermal Protection Activated / Config Mode Asked By WT Shunt",
		"Thermal Protection Activated / Double Power Cut Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Usage Not-Set Not-Paired",
		"Obstacle DOWN / Usage Set Not-Paired",
		"Obstacle DOWN / Usage Not-Set Paired",
		"Obstacle DOWN / Usage Set Paired",
		"Obstacle DOWN / Radio Setting Mode",
		"Obstacle DOWN / WT Ergo Setting Mode",
		"Obstacle DOWN / WT Shunt Setting Mode",
		"Obstacle DOWN / Config Mode Asked By Radio",
		"Obstacle DOWN / Config Mode Asked By WT Ergo",
		"Obstacle DOWN / Config Mode Asked By WT Shunt",
		"Obstacle DOWN / Double Power Cut Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / Usage Not-Set Not-Paired",
		"Obstacle DOWN / Thermal Protection Activated / Usage Set Not-Paired",
		"Obstacle DOWN / Thermal Protection Activated / Usage Not-Set Paired",
		"Obstacle DOWN / Thermal Protection Activated / Usage Set Paired",
		"Obstacle DOWN / Thermal Protection Activated / Radio Setting Mode",
		"Obstacle DOWN / Thermal Protection Activated / WT Ergo Setting Mode",
		"Obstacle DOWN / Thermal Protection Activated / WT Shunt Setting Mode",
		"Obstacle DOWN / Thermal Protection Activated / Config Mode Asked By Radio",
		"Obstacle DOWN / Thermal Protection Activated / Config Mode Asked By WT Ergo",
		"Obstacle DOWN / Thermal Protection Activated / Config Mode Asked By WT Shunt",
		"Obstacle DOWN / Thermal Protection Activated / Double Power Cut Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Usage Not-Set Not-Paired",
		"Obstacle UP / Usage Set Not-Paired",
		"Obstacle UP / Usage Not-Set Paired",
		"Obstacle UP / Usage Set Paired",
		"Obstacle UP / Radio Setting Mode",
		"Obstacle UP / WT Ergo Setting Mode",
		"Obstacle UP / WT Shunt Setting Mode",
		"Obstacle UP / Config Mode Asked By Radio",
		"Obstacle UP / Config Mode Asked By WT Ergo",
		"Obstacle UP / Config Mode Asked By WT Shunt",
		"Obstacle UP / Double Power Cut Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / Usage Not-Set Not-Paired",
		"Obstacle UP / Thermal Protection Activated / Usage Set Not-Paired",
		"Obstacle UP / Thermal Protection Activated / Usage Not-Set Paired",
		"Obstacle UP / Thermal Protection Activated / Usage Set Paired",
		"Obstacle UP / Thermal Protection Activated / Radio Setting Mode",
		"Obstacle UP / Thermal Protection Activated / WT Ergo Setting Mode",
		"Obstacle UP / Thermal Protection Activated / WT Shunt Setting Mode",
		"Obstacle UP / Thermal Protection Activated / Config Mode Asked By Radio",
		"Obstacle UP / Thermal Protection Activated / Config Mode Asked By WT Ergo",
		"Obstacle UP / Thermal Protection Activated / Config Mode Asked By WT Shunt",
		"Obstacle UP / Thermal Protection Activated / Double Power Cut Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Usage Not-Set Not-Paired",
		"Obstacle UP / Obstacle DOWN / Usage Set Not-Paired",
		"Obstacle UP / Obstacle DOWN / Usage Not-Set Paired",
		"Obstacle UP / Obstacle DOWN / Usage Set Paired",
		"Obstacle UP / Obstacle DOWN / Radio Setting Mode",
		"Obstacle UP / Obstacle DOWN / WT Ergo Setting Mode",
		"Obstacle UP / Obstacle DOWN / WT Shunt Setting Mode",
		"Obstacle UP / Obstacle DOWN / Config Mode Asked By Radio",
		"Obstacle UP / Obstacle DOWN / Config Mode Asked By WT Ergo",
		"Obstacle UP / Obstacle DOWN / Config Mode Asked By WT Shunt",
		"Obstacle UP / Obstacle DOWN / Double Power Cut Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Usage Not-Set Not-Paired",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Usage Set Not-Paired",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Usage Not-Set Paired",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Usage Set Paired",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Radio Setting Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / WT Ergo Setting Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / WT Shunt Setting Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Config Mode Asked By Radio",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Config Mode Asked By WT Ergo",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Config Mode Asked By WT Shunt",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / Double Power Cut Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode",
		"Obstacle UP / Obstacle DOWN / Thermal Protection Activated / !!! Undefined Mode"
	}

	if title == "Actuator_Status" then
		return Actuator_Status
	end
end

return TableValues
