#!/bin/sh

case "$1" in
  start)
    mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc

    echo 1 > /proc/sys/fs/binfmt_misc/status
    for conf in /etc/binfmt.d/*.conf ; do
      cat $conf > /proc/sys/fs/binfmt_misc/register
    done
    ;;
  stop)
    echo -1 > /proc/sys/fs/binfmt_misc/status
    echo 0 > /proc/sys/fs/binfmt_misc/status
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
