#!/bin/sh

. /usr/share/kizosenv.sh

bootcount_reset() {
  [ -f /etc/default/rcS ] && . /etc/default/rcS
  [ "$VERBOSE" != no ] && echo "Setting bootcount to 0"
  # u-boot count
  if have_u_boot; then
    echo "0" > /sys/uboot/count
  else
    echo "0" > /persistent/boot/boot_count_file
    sync
  fi
}

case "$1" in
  start)
    bootcount_reset
    /usr/share/bsp/manage-persistent-spare.sh "notify"
    ;;
  *)
    echo "Usage: /etc/init.d/bootcount-reset {start}"
    exit 1
esac

exit 0

