#!/bin/sh

set -e

DAEMON=`which watchdog`
NAME="Watchdog"
WDOG_RST=15
WDOG_TOUT=60
WDOG_DEV=/dev/watchdog0

ARGS=" -t $WDOG_RST -T $WDOG_TOUT $WDOG_DEV"

if [ -e $WDOG_DEV ]
then
  $DAEMON $ARGS
else
  echo "$WDOG_DEV doesn't exist"
  exit 1
fi

exit 0
