#!/bin/sh

# First prototypes has the ethmac file, this test might be removed later on

iface=${IFACE:-eth0}

case "$1" in
start)
	if ! readlink -f "/sys/class/net/$iface/device/driver" | grep -q macb ; then
		echo "GMAC ethernet is disabled"
		exit 0
	fi

	if ! ip -o link show up | grep -q "$iface"; then
		ethmac=$ETHMAC
		if [ -z "$ethmac" ]; then
			if ! ethmac=$(cat /etc/security/ethmac-$iface 2>/dev/null) &&
			   ! ethmac=$(cat /etc/security/ethmac        2>/dev/null); then
				echo "$iface: No /etc/security/ethmac[-$iface] files!"
			fi
		fi

		[ -z "$ethmac" ] && exit 0
		ethmac=${ethmac:-F8:81:1A:00:00:00}
		ip link set addr $ethmac dev $iface
	fi
	;;
esac
