#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/lighttpd
NAME=lighttpd
DESC="Lighttpd Web Server"
OPTS="-f /etc/lighttpd/lighttpd.conf"
PIDF=/var/run/lighttpd.pid

is_running() {
	if $0 status >/dev/null; then
		return 0
	else
		return 1
	fi
}

# set loop_n sleep_t (ms)
wait_notrunning() {
	[ "$#" -eq 2 ] || { echo "WRONG args count $#"; exit 1; }
	local loop=0
	while is_running; do
		[ "$loop" -lt "$1" ] || return 1
		_=$((loop++))
		usleep $(($2 * 1000))
	done
}

case "$1" in
	start)
		if is_running; then
			logger -t "initscript" -p user.warn "${DAEMON##*/}: already started.  EXIT."
			exit 0
		else
			[ -z "$OVK_LISTENING_PORTS" ] && export OVK_LISTENING_PORTS=443
		fi

		mkdir -p "/var/volatile/crt"
		cat  /etc/security/ca.crt /etc/security/app_ca.crt > "/var/volatile/crt/CA_all.crt"
		if [ -f /etc/security/webserver_ca.crt ]; then
			cat  /etc/security/webserver.crt /etc/security/webserver_ca.crt > "/var/volatile/crt/Chain.crt"
		else
			cat  /etc/security/webserver.crt /etc/lighttpd/ssl/overkiz/CA_intermediate.crt > "/var/volatile/crt/Chain.crt"
		fi

		# Ensure to have the correct CRL file at correct place
		mkdir -p "/persistent/root/etc/ssl" "/var/volatile/crl"
		cp -u "/etc/ssl/crl/local-apps-crl.pem" "/persistent/root/etc/ssl/local-apps-crl.pem"
		cat "/persistent/root/etc/ssl/local-apps-crl.pem" "/etc/ssl/crl/local-root-crl.pem" >"/var/volatile/crl/local-apps-crl.pem"

		if ! $DAEMON $OPTS; then
			logger -t "initscript" -p user.err "${DAEMON##*/}: failed to start."
			exit 1
		fi
		;;
	status)
		pid=$(cat $PIDF 2> /dev/null || echo)
		if test -n "$pid"; then
			[ "$(cat /proc/$pid/comm 2> /dev/null || echo)" = "${DAEMON##*/}" ] || exit 1
			if [ "$1" = wait ]; then
				wait $pid
			fi
			echo "$pid"
		else
			# There might be cases where PIDF is not filled (running in
			# foreground?)
			if ! pid=$(pidof -s ${DAEMON##*/}); then
				exit 1
			fi
		fi
		;;
	stop)
		if ! pid=$($0 status) || test -z "$pid"; then
			echo "already stopped."
			exit 0
		fi
		kill "$pid" >/dev/null

		wait_notrunning 10 200 || {
			logger -t "initscript" -p user.warn "${DAEMON##*/}: Force killing."
			kill -SIGKILL "$pid"
			rm -f $PIDF
		}
		;;
	restart|force-reload)
		$0 stop || true
		wait_notrunning 10 500 || {
			logger -t "initscript" -p user.warn "${DAEMON##*/}: force starting."
		}
		$0 start > /dev/null
		;;
	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
