#!/bin/sh
#
# Run the mdev daemon
#

DAEMON="mdev"
PIDFILE="/var/run/$DAEMON.pid"


start() {
  echo -n "Starting $DAEMON... "
  start-stop-daemon -S -b -m -p $PIDFILE -x /sbin/mdev -- -df
  [ $? -eq 0 ] && echo "OK" || echo "ERROR"

  # coldplug modules
  find /sys/ -name modalias -print0 | \
    xargs -0 sort -u | \
    tr '\n' '\0' | \
    xargs -0 modprobe -abq

# Run add event to usb buses. Needed for coldplug. 
#for bus in $(find /sys/bus/usb/devices/*/uevent); do echo -n add >$bus; done 

sysctl -e -p /etc/sysctl.conf >/dev/null
}

stop() {
  echo -n "Stopping $DAEMON... "
  start-stop-daemon -K -p $PIDFILE
  [ $? -eq 0 ] && echo "OK" || echo "ERROR"
}

restart() {
  stop
  start
}

case "$1" in
  start|stop|restart)
  "$1"
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?

