#!/bin/sh
set -e

mount | grep -qs /sys  || mount /sys

case "$1" in
  start)
    shift
    if ! at91-gpio status -q PE3 | grep -q -c 'out 1' ; then
      at91-gpio export -q PE3 1
    fi
    ;;
  stop)
    shift
    at91-gpio output -q PE3 0
    ;;
  restart|reload)
    shift
    $0 stop || true
    sleep 1
    $0 start
    ;;
  force-stop)
    shift
    at91-gpio unexport -q PE3 0
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-stop|export|unexport}" >&2
    exit 1
    ;;
esac

exit 0
